### ISSUE TITLE
Should now_lambda come into this repository?

### ISSUE THREAD

**Issue by amaurymartiny** [mike-engel/now-rust#13]
**Is your feature request related to a problem? Please describe.**

https://crates.io/crates/now_lambda seems to be unmaintained, and its repo points to an [archived Github repository](https://github.com/zeit/now-builders).

Yet, to quote the author,

> The required dependency is now_lambda which provides all of the resources needed to provide the serverless runtime.

So this repo heavily relies on a hidden & unmaintained `now_lambda`

**Describe the solution you'd like**

Maybe put now_lambda into this repository too? Or remove that dependency altogether?

**Describe alternatives you've considered**

Maybe use https://github.com/awslabs/aws-lambda-rust-runtime?

**Comment by anmonteiro** [comment]
This repository _is_ `now_lambda` and it does use the official Rust runtime by AWS

**Comment by amaurymartiny** [comment]
Ah ok! All good then.

A small action item would then just to update the repository link on crates.io.
