### ISSUE TITLE
Cannot access shared libraries

### ISSUE THREAD

**Issue by mike-engel** [mike-engel/now-rust#2]
> **Note**: This was transferred from the official [now-builders](https://github.com/zeit/now-builders/issues/361) repo.

I'm using a library that uses [pq-sys](https://github.com/sgrif/pq-sys), which tries to load `libpq` at runtime. Whenever the lambda is invoked, it encounters this error:

```
/var/task/bootstrap: error while loading shared libraries: libpq.so.5:
cannot open shared object file: No such file or directory
```

I'm not familiar with this stuff, but I managed to verify that:
- `libpq.so.5` is located in `/usr/lib64`
- `LD_LIBRARY_PATH` includes `/usr/lib64`
- `PQ_LIB_DIR` includes `/usr/lib64`

It seems the lambda is not able access shared libraries at runtime. Here's an [example deployment](https://diesel-issue-demo-5777l3xa5.now.sh/_src) for reference.

**Comment by jacobmischka** [comment]
Bummer about musl being more difficult than anticipated. I'm not super familiar with AWS lambdas, is accessing shared libraries possible or is static linking the only way forward?

It really doesn't matter to me how it happens, but it would be wonderful if I could get rust to talk to a Postgres database in any way at all.

Thanks for your continued help with this!

**Comment by mike-engel** [comment]
One option I could see is to include shared libraries in the build as static files. You would have to change the environment variables/rust configuration to look in that place rather than in the normal locations, but that could be an alternative.

Admittedly I don't have a ton of systems knowledge here, so I don't know why diesel requires static links vs. dynamic ones (or maybe that was just the solution for now lambdas).

**Comment by jacobmischka** [comment]
Yeah that was just the solution for the lambdas, dynamic links work just fine in other environments.

Thanks for the suggestion, I'm going to try that for a while. Bummer that the iteration loop is just so long, compiling for 5 minutes just to get the same error as before is starting to get soul crushing ha.

**Comment by mike-engel** [comment]
@jacobmischka I totally understand that! I've been there many times before. Hopefully #1 will help 😄

**Comment by jacobmischka** [comment]
Hey, that was significantly easier than I thought, thanks so much for your direction.

I was able to get it to successfully use the libraries by including a `lib` directory containing the necessary `.so` files, and using the following `now.json`:

```json
{
	"version": 2,
	"builds": [
		{
			"src": "Cargo.toml",
			"use": "now-rust",
			"config": {
				"includeFiles": [
					"lib/**",
				]
			}
		}
	],
	"env": {
		"LD_LIBRARY_PATH": "lib/"
	},
	"build": {
		"env": {
			"MYSQLCLIENT_LIB_DIR": "lib",
			"LD_LIBRARY_PATH": "lib/"
		}
	}
}
```

**Comment by mike-engel** [comment]
Wonderful! So glad it worked for you and that we have a nice alternative. I'll add it to the README soon. Thanks for testing!
