### ISSUE TITLE
failed to yum install -y openssl-devel

### ISSUE THREAD

**Issue by lilith** [mike-engel/now-rust#21]
**Describe the bug**
Duplicate of https://github.com/zeit/now/issues/2087 , but happens on the latest vercel CLI

**To Reproduce**
Steps to reproduce the behavior.
Run `now dev` on example code in README

**Logs**
```

To configure your current shell run source $HOME/.cargo/env
installing openssl-devel...
failed to `yum install -y openssl-devel`
Error: spawn yum ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn yum',
  path: 'yum',
  spawnargs: [ 'install', '-y', 'openssl-devel' ],
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd: 'yum install -y openssl-devel',
  timedOut: false,
  killed: false
}

```

**Environment (please complete the following information):**
```
$ now --version
Now CLI 18.0.0
18.0.0
$ rustc --version
rustc 1.43.0 (4fb7144ed 2020-04-20)
```
 - rust stable 1.43
 - rust edition 2018
 - now-rust (Building now-rust@1.0.0)

**Additional context**

**Comment by mike-engel** [comment]
@lilith could you provide your `now.json`?

**Comment by lilith** [comment]
It's from the readme: 

```
{
	"functions": {
		"api/**/*.rs": {
			"runtime": "now-rust@1.0.0"
		}
	}
}
```

**Comment by lilith** [comment]
Hey, it works if I change it to 2.0.0! Maybe the readme should be updated?

**Comment by mike-engel** [comment]
Yep, I missed this during the 2.0.0 release. I've updated the readme on github now. Thanks!
