### ISSUE TITLE
Environment variables not available at compile time

### ISSUE THREAD

**Issue by fliepeltje** [mike-engel/now-rust#26]
**Describe the bug**
When using variables that need to get injected at compile-time the build fails when pushed to Vercel. 

**To Reproduce**
1. Set secret in the vercel project dashboard (e.g. `FOO=foo`)
2. In your endpoint handler extract the variable with the `env` macro (e.g. `let foo = env!("FOO")`)

Then the build will fail

**Expected behavior**
The expectation is that the secrets are available as env variables as is the case for other runtimes.

**Logs**
Relevan build log output:
```
16:29:04.773  
To get started you need Cargo's bin directory ($HOME/.cargo/bin) in your PATH
16:29:04.773  
environment variable. Next time you log in this will be done
16:29:04.773  
automatically.
16:29:04.773  
To configure your current shell run source $HOME/.cargo/env
16:29:25.299  
error: environment variable `FOO` not defined
16:29:25.299  
  --> register.rs:28:18
16:29:25.299  
   |
16:29:25.299  
28 |     let secret = env!("FOO");
16:29:25.299  
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
16:29:25.400  
error: aborting due to previous error
16:29:25.424  
error: could not compile `api`.
16:29:25.424  
To learn more, run the command again with --verbose.
16:29:25.427  
failed to `cargo build`
16:29:25.429  
Error: Command failed: cargo build --bin register --quiet --release
16:29:25.429  
    at makeError (/vercel/c9729a1f551aeb28/.build-utils/.builder/node_modules/execa/index.js:174:9)
16:29:25.429  
    at /vercel/c9729a1f551aeb28/.build-utils/.builder/node_modules/execa/index.js:278:16
16:29:25.429  
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
16:29:25.429  
    at async buildSingleFile (/vercel/c9729a1f551aeb28/.build-utils/.builder/node_modules/now-rust/dist/index.js:100:9)
```

**Environment (please complete the following information):**
 - rust [stable]
 - rust edition [2018]
 - now-rust [latest]

**Additional context**
The build logs also contain the following lines: 

```
16:29:28.656  
warning: $HOME differs from euid-obtained home directory: you may be using sudo
16:29:28.656  
warning: $HOME directory: "/vercel"
16:29:28.656  
warning: euid-obtained home directory: /root
```

according to [this post](https://stackoverflow.com/questions/40604084/cant-access-environment-variable-in-rust) the env variables can get reset when running cargo with sudo. This might explain why the env variables are not avaialble.

**Comment by fliepeltje** [comment]
As it turns out, my configuration was incorrect.

**Comment by Alounv** [comment]
> As it turns out, my configuration was incorrect. 

Since I might have a similar issue (but at runtime) could you please tell how your setup was wrong and how you corrected it?
Thanks!
