### ISSUE TITLE
contents changed in original source code when running now dev

### ISSUE THREAD

**Issue by mike-engel** [mike-engel/now-rust#3]
> **Note**: This was transferred from the official [now-builders](https://github.com/zeit/now-builders/issues/589) repo.

Not sure if I should post this here or in `now-cli` repo, but here it is:

When running `now dev` with `@now/rust` builder using `index.rs` entry point, it keeps changing the content of `Cargo.toml` and `index.rs`

#### Changes in `Cargo.toml`
```diff
[[bin]]
name = "index"
-path = "index.rs"
+path = "/Users/fatih/dev/paper/services/embed/github/index.rs"
```

#### Changes in `index.rs`
```diff
+use now_lambda::lambda;
+use std::error::Error;

// my handler code here

+fn main() -> Result<(), Box<dyn Error>> {
+    Ok(lambda!(handler))
+}
```

The problem is I'm not supposed to commit this changes, and I think this change should only be applied in private copy (somewhere in `/var/private`?).

Another problem is when running `now dev` again, it will add another template over and over again, it's possible that I get something like this

```diff
+use now_lambda::lambda;
+use std::error::Error;

+use now_lambda::lambda;
+use std::error::Error;

+use now_lambda::lambda;
+use std::error::Error;

// my handler code here

+fn main() -> Result<(), Box<dyn Error>> {
+    Ok(lambda!(handler))
+}

+fn main() -> Result<(), Box<dyn Error>> {
+    Ok(lambda!(handler))
+}


+fn main() -> Result<(), Box<dyn Error>> {
+    Ok(lambda!(handler))
+}
```

## My config

`now.json`
```json
{
  "builders": [
    {
      "src": "services/embed/**/index.rs",
      "use": "@now/rust@canary"
    },
  ]
}
```

## Version
```sh
❯ now --version
15.4.0
❯ uname -a
Darwin TVLK-FatihKalifa.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
❯ cargo --version
cargo 1.35.0 (6f3e9c367 2019-04-04)
```

**Comment by cbrevik** [comment]
Is there any way to get around this? Been trying to use `now-rust`, but this (and a few other bugs) make it a bit difficult.

**Comment by mike-engel** [comment]
@cbrevik unfortunately I'm still working on #1 as I get time. If you'd like to help, let me know

**Comment by cbrevik** [comment]
Sure @mike-engel, let me look it over later to see if I can help. 

The main one I had trouble with was using `now-cli@16.1.1` with `now-rust`, I can submit an issue with reproduction for that.

**Comment by cbrevik** [comment]
I was looking at the PR earlier thinking of helping out. Tried cloning this project and referencing/debugging it from an adjacent test project, but I am having some issues. Do you know if there is any documentation/guides on developing/debugging now-builders locally?

**Comment by mike-engel** [comment]
@cbrevik No, unfortunately not 😞 The best I can think of right now is an `npm link` or `npm install ../path/to/fork`. I haven't personally had too much luck with those, but you may try browsing [spectrum](https://spectrum.chat/zeit?tab=posts) or looking through the issues on [now](https://github.com/zeit/now). Sorry I can't be too much help right now. I'm preparing to move a long distance, but afterward can help more 😄
