### ISSUE TITLE
now dev is not working on Windows O.S.

### ISSUE THREAD

**Issue by corentinway** [mike-engel/now-rust#9]
**Describe the bug**
The error message iss saying 
ENOENT: no such file or directory, open 'C:\Users\xxxxxxx\api\from-email\target\release\fromemail' 
It seems that

1. the `.exe` extension file is not happened to the binary name
2. the build script is not testing if the file exists. It is failing at runtime.

**To Reproduce**
run now dev and now rust on windows OS.

**Expected behavior**
rust function is working

**Logs**
error message : 

ENOENT: no such file or directory, open 'C:\Users\xxxxxxx\api\from-email\target\release\fromemail'

**Environment (please complete the following information):**
 - rust stable
 - rust edition 2018
 - now-rust latest 

**Additional context**

**Comment by mike-engel** [comment]
@corentinway This should now be working. Thanks for your patience.

**Comment by remidebette** [comment]
Hi!

I wanted to test this but apparently now-rust@2.0.1 is not published on npm.

Should we use a different version?
Thanks

**Comment by mike-engel** [comment]
@remidebette sorry about that. Not sure what happened since I thought I published it. It should be up now.

**Comment by remidebette** [comment]
I confirm I can run the sample code on windows now, thanks!

(you might want to update the sample in the README to use 2.0.1)
